import java.awt.Font;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;

public class Tela extends javax.swing.JFrame 
{
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Tela.class.getName());
    
    private Font fNormal, fNegrito, fItalico, fNegritoItalico;
    
    private String nomes[] = {"Selecione uma imagem", "casa.jpeg", "pessoa.jpg", "aviao.jpg", "gato.jpg"};
    private ImageIcon icones[] = {
        new ImageIcon (nomes[0]), new ImageIcon(nomes[1]), new ImageIcon(nomes[2]), new ImageIcon(nomes[3]), new ImageIcon(nomes[4])
    };

    public Tela() 
    {
        initComponents();
        
        fNormal         = new Font("TimesRoman", Font.PLAIN, 18);
        fNegrito        = new Font("TimesRoman", Font.BOLD, 18);
        fItalico        = new Font("TimesRoman", Font.ITALIC, 18);
        fNegritoItalico = new Font("TimesRoman", Font.BOLD + Font.ITALIC, 18);
        
        RadioButtonHandler rBtnHandler = new RadioButtonHandler();
        
        rbnNormal.addItemListener(rBtnHandler);
        rbnNegrito.addItemListener(rBtnHandler);
        rbnItalico.addItemListener(rBtnHandler);
        rbnNegritoItalico.addItemListener(rBtnHandler);
        
        // --------------------------------------------------------------------------
        
        DefaultComboBoxModel cbm = new DefaultComboBoxModel();
        
        for (int i = 0; i < nomes.length; i++)
        {
            cbm.addElement(nomes[i]);
        }
        
        cmbImagens.setModel(cbm);
        
        cmbImagens.addItemListener(new ItemListener(){
            public void itemStateChanged(ItemEvent e) 
            {
                lblImagem.setIcon(icones[cmbImagens.getSelectedIndex()]);
            }
        });
    }
    
    public class RadioButtonHandler implements ItemListener
    {

        @Override
        public void itemStateChanged(ItemEvent e) 
        {
            if (e.getSource() == rbnNormal)
            {
                tfdTexto.setFont(fNormal);
            }
            
            if (e.getSource() == rbnNegrito)
            {
                tfdTexto.setFont(fNegrito);
            }
            
            if (e.getSource() == rbnItalico)
            {
                tfdTexto.setFont(fItalico);
            }
            
            if (e.getSource() == rbnNegritoItalico)
            {
                tfdTexto.setFont(fNegritoItalico);
            }
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btg = new javax.swing.ButtonGroup();
        tfdTexto = new javax.swing.JTextField();
        rbnNormal = new javax.swing.JRadioButton();
        rbnNegrito = new javax.swing.JRadioButton();
        rbnItalico = new javax.swing.JRadioButton();
        rbnNegritoItalico = new javax.swing.JRadioButton();
        cmbImagens = new javax.swing.JComboBox<>();
        lblImagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tfdTexto.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        tfdTexto.setText("Me modifique!");
        tfdTexto.addActionListener(this::tfdTextoActionPerformed);

        btg.add(rbnNormal);
        rbnNormal.setText("Normal");

        btg.add(rbnNegrito);
        rbnNegrito.setText("Negrito");

        btg.add(rbnItalico);
        rbnItalico.setText("Italico");

        btg.add(rbnNegritoItalico);
        rbnNegritoItalico.setText("Negrito/Italico");

        cmbImagens.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(336, 336, 336)
                .addComponent(rbnNormal)
                .addGap(35, 35, 35)
                .addComponent(rbnNegrito)
                .addGap(34, 34, 34)
                .addComponent(rbnItalico)
                .addGap(18, 18, 18)
                .addComponent(rbnNegritoItalico)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbImagens, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(tfdTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(186, 186, 186))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(tfdTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbnNormal)
                    .addComponent(rbnNegrito)
                    .addComponent(rbnItalico)
                    .addComponent(rbnNegritoItalico))
                .addGap(41, 41, 41)
                .addComponent(cmbImagens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfdTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdTextoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Tela().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btg;
    private javax.swing.JComboBox<String> cmbImagens;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JRadioButton rbnItalico;
    private javax.swing.JRadioButton rbnNegrito;
    private javax.swing.JRadioButton rbnNegritoItalico;
    private javax.swing.JRadioButton rbnNormal;
    private javax.swing.JTextField tfdTexto;
    // End of variables declaration//GEN-END:variables
}
