import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.*;

public class Tela extends javax.swing.JFrame 
{
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Tela.class.getName());

    public Tela() 
    {
        initComponents();
        lblRotulo1.setToolTipText("Oi");
        
        ImageIcon imagem = new ImageIcon("cliente.png");
        lblRotulo1.setIcon(imagem);
        lblRotulo1.setHorizontalTextPosition(SwingConstants.RIGHT); // alinhamento horizontal
        lblRotulo1.setVerticalTextPosition(SwingConstants.CENTER); // alinhamento vertical
        
        // ----------------------------------------------------------------------------------------
        // tfdNome.setEditable(false); // n da mais pra editar
        // tfdNome.setEnabled(false); // text field fica cinzinha (desativado)
        
        TextFieldHandler txt_handler = new TextFieldHandler();
        tfdNome.addActionListener(txt_handler);
        pfdSenha.addActionListener(txt_handler);
        
        // ----------------------------------------------------------------------------------------
        
        ImageIcon imagem_btn = new ImageIcon("botao.png");
        btnIcone.setIcon(imagem_btn);
        btnIconeRolavel.setRolloverIcon(imagem_btn);
        
        ButtonHandler btn_handler = new ButtonHandler();
        btnIcone.addActionListener(btn_handler);
        btnIconeRolavel.addActionListener(btn_handler);
        
        // ----------------------------------------------------------------------------------------
        
        CheckBoxHandler cbx_handler = new CheckBoxHandler();
        cbxNegrito.addItemListener(cbx_handler);
        cbxItalico.addItemListener(cbx_handler);
        
    }
    
    public class TextFieldHandler implements ActionListener
    {
        public void actionPerformed(ActionEvent e)
        {
            String s = "";
            
            if (e.getSource() == tfdNome)
            {
                s = "Campo de texto nome: " + e.getActionCommand();
            }
            else if (e.getSource() == pfdSenha)
            {
                s = "Campo de senha: " + e.getActionCommand();
            }
            
            JOptionPane.showMessageDialog(null, s);
        }
    }
    
    public class ButtonHandler implements ActionListener
    {
        public void actionPerformed(ActionEvent e)
        {   
            JOptionPane.showMessageDialog(null, "Voce pressionou " + e.getActionCommand());
        }
    }
    
    private class CheckBoxHandler implements ItemListener
    {
        private int valNegrito = Font.PLAIN;
        private int valItalico = Font.PLAIN;
        
        public void itemStateChanged(ItemEvent e)
        {
            if (e.getSource() == cbxItalico)
            {
                if (e.getStateChange() == ItemEvent.SELECTED)
                    valItalico = Font.ITALIC;
                else
                    valItalico = Font.PLAIN;
            }
            
            if (e.getSource() == cbxNegrito)
            {
                if (e.getStateChange() == ItemEvent.SELECTED)
                    valNegrito = Font.BOLD;
                else
                    valNegrito = Font.PLAIN;
            }
            
            tfdTexto.setFont(
                new Font("Times Roman", valNegrito + valItalico, 18)
            );
            tfdTexto.repaint();
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRotulo1 = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        tfdNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        pfdSenha = new javax.swing.JPasswordField();
        btnIcone = new javax.swing.JButton();
        btnIconeRolavel = new javax.swing.JButton();
        tfdTexto = new javax.swing.JTextField();
        cbxNegrito = new javax.swing.JCheckBox();
        cbxItalico = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblRotulo1.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblRotulo1.setText("Teste de Label");

        lblNome.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblNome.setText("Nome:");

        tfdNome.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel1.setText("Senha:");

        pfdSenha.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N

        btnIcone.setText("Botao com icone");
        btnIcone.addActionListener(this::btnIconeActionPerformed);

        btnIconeRolavel.setText("Botao com Icone rolavel");
        btnIconeRolavel.addActionListener(this::btnIconeRolavelActionPerformed);

        tfdTexto.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        tfdTexto.setText("Me modifique abaixo:");
        tfdTexto.addActionListener(this::tfdTextoActionPerformed);

        cbxNegrito.setText("Negrito");

        cbxItalico.setText("Italico");
        cbxItalico.addActionListener(this::cbxItalicoActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(360, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxItalico)
                    .addComponent(cbxNegrito)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNome)
                        .addGap(18, 18, 18)
                        .addComponent(tfdNome, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblRotulo1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnIcone, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnIconeRolavel, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pfdSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(tfdTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(291, 291, 291))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(lblRotulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfdNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNome))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(pfdSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIcone, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIconeRolavel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(tfdTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbxNegrito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxItalico)
                .addContainerGap(292, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIconeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIconeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIconeActionPerformed

    private void btnIconeRolavelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIconeRolavelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIconeRolavelActionPerformed

    private void tfdTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdTextoActionPerformed

    private void cbxItalicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxItalicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxItalicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Tela().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIcone;
    private javax.swing.JButton btnIconeRolavel;
    private javax.swing.JCheckBox cbxItalico;
    private javax.swing.JCheckBox cbxNegrito;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblRotulo1;
    private javax.swing.JPasswordField pfdSenha;
    private javax.swing.JTextField tfdNome;
    private javax.swing.JTextField tfdTexto;
    // End of variables declaration//GEN-END:variables
}
